Massive update, should have split into >1 commit
- adding ruby and python packages to the features
- updated atom packages and latest config
- including gitconfig to remove depdendency on sproutwrap
- removing rbenv and python from sproutwrap
- global rename of $status to $last_command_status
- globally added $runner_status
- added -i and -I flags to ignore statement errors
  and runner errors

- attempted to implement exception handling
  using trap and USR1, which is yet untested.
  It's only activated when -I flag is passed.

diff --git a/pu b/pu
--- a/pu
+++ b/pu
@@ -12,28 +12,25 @@
 function setup {
   export original_dir=$(pwd)
   export pu_home="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-
   cd ${pu_home}
   source "lib/pu-loader"
-
 }
 
 setup
-
 opts_features=""
 
-while getopts "ar:SBPLIRKFCfqnvlhHxpZTt:" opt; do
+while getopts "ar:SBPLiIRKFCfqnvlhHxpZTt:" opt; do
   case $opt in
     a)
-    export runners=${installers}          ;;
+      export runners=${installers}  ;;
     r)
-    [[ "${OPTARG}" == "sudo-enable"  ]] && export skip_sudo_disable=true
-    [[ "${OPTARG}" == "sudo-disable" ]] && export sudoers_enabled=true
-    if [ -z "$runners" ]; then
-      export runners="$OPTARG"
-    else
-      export runners="$runners $OPTARG"
-    fi                                    ;;
+      [[ "${OPTARG}" == "sudo-enable"  ]] && export skip_sudo_disable=true
+      [[ "${OPTARG}" == "sudo-disable" ]] && export sudoers_enabled=true
+      if [ "${#runners}" -eq 0 ]; then
+        runners="$OPTARG"
+      else
+        runners+=" $OPTARG"
+      fi                                    ;;
 
     #========================= Features     =========================
 
@@ -51,7 +48,9 @@ while getopts "ar:SBPLIRKFCfqnvlhHxpZTt:" opt; do
     f)
       export opts_force=" --force "         ;;
     I)
-      export opts_ignore_errors=yes         ;;
+      export opts_continue_on_runner_error=yes       ;;
+    i)
+      export opts_continue_on_statement_error=yes    ;;
     P)
       export opts_rsync_backup=             ;;
 
@@ -114,8 +113,42 @@ while getopts "ar:SBPLIRKFCfqnvlhHxpZTt:" opt; do
   esac
 done
 
-function main {
+function continue_next_runner() {
+  run_runners "${runners_list[@]}"
+}
 
+trap USR1 continue_next_runner
+
+function run_runners() {
+  while (( "$#" )); do
+    runner=$1
+    # my arrays start with a 1
+    runners_started=$((runners_started + 1))
+
+    [[ $runners_started -eq 1 ]] && pu-short-header
+
+    # I so much rather prefer dashes in the function and file names than underscores.
+    # Dashes just feel like a continuation. Underscores are from another era. Jurassic.
+    pu-print-section-header ${runner}
+
+    export runner_status=0
+    eval ${runner}
+    runner_status=${runner_status:-1}
+
+    if [ ${runner_status} -ne 0 ]; then
+      printf "${bldred}error: runner ${bldred}${runner}${bldwht} exited with status: ${bakred} ${runner_status} ${txtrst}\n"
+      [[ ${opts_continue_on_runner_error} ]] || abort $runner_status
+      printf "${bldgrn}       ignoring error due to the flag set.${txtrst}\n"
+      runners_ignored=$((runners_ignored + 1))
+    else
+      runners_completed=$(($runners_completed + 1))
+    fi
+    shift
+    declare -a runners_list=$@
+  done
+}
+
+function main {
   # Load package definitions based on the <-t template> setting.
   package-config
 
@@ -126,36 +159,18 @@ function main {
   # or to something specific passed via the flag. It should not be blank.
   [[ -z "${runners}" ]] || on_start
 
-  local runners_started=0
-  local runners_ignored=0
-  local runners_completed=0
+  export runners_started=0
+  export runners_ignored=0
+  export runners_completed=0
+  export runners_aborted=0
 
   export commands_failed=0
   export commands_completed=0
   export commands_ignored=0
 
-  for runner in $runners; do
-    # my arrays start with a 1
-    export runners_started=$((runners_started + 1))
+  declare -a runners_list=($runners)
 
-    [[ $runners_started -eq 1 ]] && pu-short-header
-
-    # I so much rather prefer dashes in the function and file names than underscores.
-    # Dashes just feel like a continuation. Underscores are from another era. Jurassic.
-    pu-print-section-header ${runner}
-
-    export status=
-    eval ${runner}
-    status=${status:-1}
-
-    if [ ${status:-1} -ne 0 ]; then
-      printf "${bldred}Non-zero status ${status} from '${runner}' runner :( ...\n${txtrst}"
-      [[ ${opts_ignore_errors} ]] || abort $status
-      export runners_ignored=$((runners_ignored + 1))
-    fi
-
-    runners_completed=$(($runners_completed + 1))
-  done
+  continue_next_runner
 
   printf "\n"
   [[ ${runners_completed} -gt 0 ]]  && printf "${bldwht}%5d${bldgrn} runners succeeded\n" $runners_completed
@@ -165,12 +180,12 @@ function main {
   [[ ${commands_ignored} -gt 0 ]]   && printf "${bldwht}%5d${bldylw} commands had non-zero exit status, but were ignored\n" $runners_ignored
   [[ ${commands_failed} -gt 0 ]]    && printf "${bldwht}%5d${bldred} commands failed\n"  $commands_failed
   echo
-  [[ $status -eq 0 && $runners_completed -gt 0 ]] && finish
+  [[ $runner_status -eq 0 && $runners_completed -gt 0 ]] && finish
   [[ $runners_started -eq 0 ]] && {
     printf "${bldylw}\nNo runners were specified.${txtrst}\nPlease run $0 -h for help.\n"
     finish
   }
-  [[ $status -ne 0 ]] && abort $status
+  [[ $runner_status -ne 0 && -z "${opts_continue_on_runner_error}" ]] && abort $last_command_status
   finish
 }
 
